schema_version = "1.0.0"

id = "clear_filepaths"
version = "1.1.3"
name = "Clear Filepaths"
tagline = "Removes personal filepaths from your .blend file"
maintainer = "FlailingFog"
type = "add-on"
website = "https://github.com/FlailingFog/clear-blender-filepaths"

# Optional list defined by Blender and server, see:
# https://docs.blender.org/manual/en/dev/advanced/extensions/tags.html
tags = ["System"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-2.0-or-later"]
platforms = ["windows-x64", "macos-arm64"]

[permissions]
files = "Saves a copy of a .blend file without filepaths"
